version : '2'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: sample
      POSTGRES_PASSWORD: pass
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  web:
    build : .
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    environment:
      POSTGRES: postgres
      POSTGRES_DB: sample
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: pass

volumes:
  postgres: